# Generated by Django 3.2.2 on 2021-05-11 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_maquinaturing'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquinaturing',
            name='sequenciaFinal',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
