# Generated by Django 3.2.3 on 2021-05-13 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_maquinaturing_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='automato',
            name='filename',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
